--- #YAML:1.0
name: Digest-SHA
version: 5.01
author:
  - Mark Shelor, mshelor@comcast.net
abstract: Perl extension for SHA-1/224/256/384/512
license: perl
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Digest::SHA:
    file: SHA.pm
    version: 5.01
generated_by: Module::Build version 0.22
