# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-SHA
version:      3.1-alpha1
version_from: SHA.pm
installdirs:  site
requires:
    Digest::base:                  1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
