#!/usr/local/bin/perl

# Copyright (C) 2003 Julius C. Duque

use diagnostics;
use strict;
use warnings;
use Digest::SHA;

while (<>) {
    chomp;
    if (-f) {
        open INFILE, $_;
        my $context = new Digest::SHA;  # defaults to SHA-1
        $context->addfile(*INFILE);
        my $digest = $context->hexdigest;
        close INFILE;
        print "$digest  $_\n";
    }
}

