#!/usr/local/bin/perl

# Copyright (C) 2003 Julius C. Duque

use diagnostics;
use strict;
use warnings;
use Digest::SHA;

for (my $i = 0; $i < @ARGV; $i++) {
    my $file = $ARGV[$i];
    chomp $file;

    if (-f $file) {  # hash only regular files
        open INFILE, $file;
        my $context = new Digest::SHA 256;
        $context->addfile(*INFILE);
        my $digest = $context->hexdigest;
        print "$digest  $file\n";
        close INFILE;
    }
}

